
project_id = "ugoessvtexianltfqwps"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
shadow_port = 54320
major_version = 15

[db.pooler]
enabled = false
port = 54329
pool_mode = "transaction"
default_pool_size = 20
max_client_conn = 100

[realtime]
enabled = true
port = 54323
tenant_id = "realtime-dev"
max_concurrent_users = 200
max_events_per_second = 100
max_channels_per_client = 100
max_joins_per_second = 500
max_channel_join_rate = 50
max_messages_per_second = 1000

[studio]
enabled = true
port = 54324
api_url = "http://127.0.0.1:54321"
openai_api_key = "env(OPENAI_API_KEY)"

[inbucket]
enabled = true
port = 54325
smtp_port = 54326
pop3_port = 54327

[storage]
enabled = true
port = 54326
file_size_limit = "50MiB"
image_transformation = true

[auth]
enabled = true
port = 54327
site_url = "http://127.0.0.1:3000"
additional_redirect_urls = ["https://127.0.0.1:3000"]
jwt_expiry = 3600
enable_signup = true
enable_email_confirmations = false
enable_sms_confirmations = false
enable_phone_signup = false
enable_phone_autoconfirm = false
enable_anonymous_users = false
minimum_password_length = 6
password_requirements = "letters_digits"
security_captcha_enabled = false
security_captcha_secret = "env(CAPTCHA_SECRET)"
security_captcha_provider = "hcaptcha"
security_update_password_require_reauthentication = false
enable_manual_linking = false

[functions.create-company-checkout]
verify_jwt = true

[functions.create-driver-checkout]
verify_jwt = true

[functions.check-subscription-access]
verify_jwt = true

[functions.record-contact-view]
verify_jwt = true

[functions.stripe-webhook]
verify_jwt = false

[edge_runtime]
enabled = true
port = 54328
inspector_port = 54329
