
project_id = "ugoessvtexianltfqwps"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[auth]
enabled = true
port = 54324
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://localhost:3000"]
jwt_expiry = 3600
enable_signup = true
enable_anonymous_sign_ins = false
enable_email_confirmations = false
enable_email_autoconfirm = false
enable_phone_confirmations = false
enable_phone_autoconfirm = false

[db]
enabled = true
port = 54322
major_version = 15

[functions]
enabled = true
port = 54323

[functions.create-company-checkout]
verify_jwt = true

[functions.create-driver-checkout]
verify_jwt = true

[functions.stripe-webhook]
verify_jwt = false

[functions.check-subscription-access]
verify_jwt = true

[functions.record-contact-view]
verify_jwt = true

[realtime]
enabled = true
port = 54325
ip_version = "ipv4"

[studio]
enabled = true
port = 54324
api_url = "http://localhost:54321"

[inbucket]
enabled = true
port = 54326
smtp_port = 1025
pop3_port = 1110
