// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ugoessvtexianltfqwps.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVnb2Vzc3Z0ZXhpYW5sdGZxd3BzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk2NTc4NjAsImV4cCI6MjA2NTIzMzg2MH0.W_baTUiCSXuA2JeIr6WDIp12mey-qHB8huoPoLATtjo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);